define([], function() {
  return {
    "PropertyPaneDescription": "Settings for SpWiki",
    "BasicGroupName": "Source",
    "TitleFieldLabel": "Title",
    "TitleFieldDescription": "Always shown on the top row of the header. Clicking it returns to the start file.",
    "DefaultTitle": "SpWiki",
    "HomeButtonLabel": "Back to the start page",
    "TagGroupName": "Tags",
    "ToolbarGroupName": "Toolbar",

    "LibraryNameFieldLabel": "Document library",
    "LibraryNameFieldDescription": "Library title (for example Documents) or a folder path under the site (for example Shared Documents).",
    "StartFileFieldLabel": "Start file",
    "StartFileFieldDescription": "Shown when the page has no ?file= parameter. .md, .markdown and .html can be displayed.",
    "SiteUrlFieldLabel": "Site URL",
    "SiteUrlFieldDescription": "Leave empty to use the current site.",

    "TagFieldLabel": "Tag column 1",
    "TagFieldLabel2": "Tag column 2",
    "TagFieldLabel3": "Tag column 3",
    "TagFieldNone": "(none)",
    "TagFieldNeedsLibrary": "Set the document library first; the tag columns are read from it.",
    "TagFieldLoading": "Reading the library's columns...",
    "TagFieldNoneFound": "No column usable as a tag was found. Check the library name, and that the library has a single line of text, multiple lines of text or choice column.",
    "TagFieldReady": "{0} column(s) to choose from.",
    "TagSearchPageLabel": "Tag search page",
    "TagSearchPageDescription": "Page opened when a tag is clicked. Empty searches on this page. For example search_tag.aspx",

    "ShowTagEditorLabel": "Allow editing tags by clicking the column name",
    "ShowEditButtonLabel": "Show the Edit button at the top right",
    "ShowOpenInAppButtonLabel": "Show the Open in app button at the top right",
    "AppProtocolLabel": "URL scheme",
    "AppProtocolDescription": "An application registered for this scheme has to be installed on the reader's machine. Defaults to spmd.",

    "LoadingMessage": "Loading...",
    "NotFoundMessage": "File not found.",
    "ErrorMessage": "The file could not be loaded.",
    "LibraryNotFoundMessage": "The document library was not found. Check the library name in the web part properties.",
    "NotConfiguredMessage": "Set the document library and the start file in the web part properties.",
    "PageLabel": "Page:",

    "TagEditLabel": "Click to edit the tags",
    "EditButtonLabel": "Edit",
    "OpenInAppButtonLabel": "Open in app",


    "TagPanelTitle": "Edit tags",
    "TagTextHint": "Separate several tags with ; or ,",
    "TagNoChoices": "This column has no choices configured. Add them in the library column settings.",
    "TagFieldMissingMessage": "No tag column is configured, or it no longer exists in the library.",
    "TagSaveFailedMessage": "The tags could not be saved.",

    "TagAddLabel": "Add a new tag",
    "TagAddPlaceholder": "e.g. design; handbook",
    "TagAddDisabledPlaceholder": "Cannot add tags to this column",
    "TagAddHint": "Type a tag the column does not offer yet. Separate several with ; or ,",
    "TagAddDisabledHint": "This column only accepts its own choices. Turn on \"Can add values manually\" in the column settings to add tags here.",

    "ShowPermissionsButtonLabel": "Show the padlock (permissions)",
    "PermUnknownTitle": "See or change the permissions",
    "PermLockedTitle": "This page has its own permissions. Click to see or change them",
    "PermUnlockedTitle": "This page inherits its permissions. Click to see or change them",
    "NotFoundReasonMessage": "It may have been deleted, or you may not have permission to read it.",
    "NotFoundTreeLabel": "Pages you can open in this library",
    "BackLabel": "Back",
    "PermTitle": "Permissions",
    "PermInheritedFromLabel": "Inherited from {0}",
    "PermUniqueLabel": "Own permissions",
    "PermTeamLabel": "the team",
    "PermFolderSuffix": " folder",
    "PermSearchButton": "Search",
    "PermSearchFailedMessage": "The directory could not be searched.",
    "PermWhoLabel": "Who has access",
    "PermRestrictLabel": "Restrict access",
    "PermRestoreLabel": "Go back to inheriting",
    "PermConfirmTitle": "Please confirm",
    "PermConfirmRestrict": "\"{0}\" will stop following its parent folder. Later changes to the parent will not reach it. For a folder, everything under it is restricted too. The current permissions are copied, so this step alone locks nobody out.",
    "PermConfirmRestore": "\"{0}\" will follow its parent folder again. The permissions set here will be lost.",
    "PermConfirmYes": "Do it",
    "PermAddLabel": "Give access to",
    "PermAddPlaceholder": "Group name, person or email address",
    "PermAddButton": "Add",
    "PermRemoveLabel": "Remove",
    "PermSearchingMessage": "Searching...",
    "PermNoResultsMessage": "Nothing matched.",
    "PermBrokenTitle": "Items this setting will not reach",
    "PermBrokenIntro": "Each item below has permissions of its own. Restricting this folder leaves them exactly as they are, so they can stay visible to people you meant to shut out. Set them one by one if that matters.",
    "PermFileScopeWarning": "Per-file permissions slow the whole library down. Set permissions on folders as a rule, and on files only as an exception.",
    "PermLoadingMessage": "Reading the permissions...",
    "PermLoadFailedMessage": "The permissions could not be read.",
    "PermNoEffectMessage": "SharePoint reported no error, but the permissions did not change. Open the item's own permission page in the library to see the real state.",
    "PermChangeFailedMessage": "The permissions could not be changed.",
    "SearchRestrictedOnlyLabel": "Restricted only",
    "PermLockedShortLabel": "Restricted",
    "SearchLabel": "Search",
    "SearchTitle": "Search",
    "SearchTermPlaceholder": "What to look for",
    "SearchModeName": "By page name",
    "SearchModeContent": "In the text",
    "SearchScopeLabel": "Folder to search",
    "SearchScopePlaceholder": "Folder (empty searches the whole library)",
    "SearchSubmitLabel": "Search",
    "SearchBusyMessage": "Searching...",
    "SearchProgressMessage": "Reading the documents... {0} / {1}",
    "SearchResultCount": "{0} result(s).",
    "SearchEmptyMessage": "No page matches.",
    "SearchPromptMessage": "Type what to look for.",
    "HelpLabel": "Help",
    "ChromeFullScreenLabel": "Switch to full screen",
    "ChromeSharePointLabel": "Switch to the SharePoint view",
    "HelpTitle": "Help",
    "HelpDocumentsTitle": "Documents",
    "HelpSetupTitle": "Setting up the library commands",
    "HelpBackLabel": "← Back to help",
    "HelpCommandSetIntro": "To put the commands on the library toolbar and context menu, add one row with these values to the Tenant Wide Extensions list in the app catalog. They are built from this page, so they can be pasted as they are.",
    "HelpComponentId": "Component id",
    "HelpLocation": "Location",
    "HelpListTemplate": "List template",
    "HelpComponentProperties": "Component properties",
    "HelpExtensionsList": "Tenant wide extensions list",
    "CopyLabel": "Copy",
    "CopiedLabel": "Copied",
    "FolderPageEmptyMessage": "This folder holds no document the viewer can show.",
    "OutlineButtonLabel": "Outline (click for a popup, double click to pin it on the left)",
    "OutlineTitle": "Outline",
    "OutlineEmptyMessage": "This page has no headings.",
    "MenuButtonLabel": "Menu",
    "PathButtonLabel": "Click to rename or move",
    "NewPageTitle": "Create a new page",
    "NewPageNamePlaceholder": "File name",
    "NewPageFormatLabel": "Format",
    "NewPageOpenWithLabel": "Then",
    "NewPageOpenInSharePoint": "Edit in SharePoint",
    "NewPageOpenInApp": "Edit in the app",
    "CreateLabel": "Create",
    "LocationTitle": "Location",
    "RootLabel": "(library root)",
    "FolderEmptyMessage": "This folder holds no document the viewer can show.",
    "CreateFailedMessage": "The file could not be created.",
    "NewPageCreatedMessage": "The page was created. The editor could not be opened; use the Edit button instead.",

    "RenameTitle": "Rename or move",
    "RenameFolderLabel": "Folder",
    "RenameNameLabel": "File name",
    "RenameHint": "Library relative. An empty folder moves the file to the library root. The destination folder has to exist already.",
    "RenameFailedMessage": "The file could not be renamed.",
    "InvalidNameMessage": "The extension has to be .md, .markdown, .html or .htm.",

    "HeadingCopyLabel": "Copy a link to this heading",
    "HeadingToggleLabel": "Click to fold",
    "LinkCopiedMessage": "Link copied",
    "CodeCopyLabel": "Copy this code",
    "CodeCopiedMessage": "Code copied",

    "DirectiveEmptyMessage": "No page matches.",

    "TagSearchTitle": "Tag:",
    "TagSearchEmpty": "No page carries this tag.",

    "OpenInAppFailedMessage": "No application started. Check that something is registered for {0}: on this machine.",
    "SaveLabel": "Save",
    "CancelLabel": "Cancel",
    "CloseLabel": "Close"
  }
});
