define([], function() {
  return {
    "PropertyPaneDescription": "SpWiki の設定",
    "BasicGroupName": "参照元",
    "TitleFieldLabel": "タイトル",
    "TitleFieldDescription": "ヘッダーの一番上に常に表示されます。クリックすると開始ファイルに戻ります。",
    "DefaultTitle": "SpWiki",
    "HomeButtonLabel": "開始ページに戻る",
    "TagGroupName": "タグ",
    "ToolbarGroupName": "ツールバー",

    "LibraryNameFieldLabel": "ライブラリ名",
    "LibraryNameFieldDescription": "ライブラリのタイトル (例: ドキュメント / Documents)、またはサイト直下のフォルダーパス (例: Shared Documents)。",
    "StartFileFieldLabel": "開始ファイル",
    "StartFileFieldDescription": "URL に ?file= が無いときに表示するファイル。.md / .markdown / .html を表示できます。",
    "SiteUrlFieldLabel": "サイト URL",
    "SiteUrlFieldDescription": "空欄の場合は現在のサイトを使用します。",

    "TagFieldLabel": "タグの列 1",
    "TagFieldLabel2": "タグの列 2",
    "TagFieldLabel3": "タグの列 3",
    "TagFieldNone": "(使用しない)",
    "TagFieldNeedsLibrary": "先に「ライブラリ名」を設定すると、タグに使える列を選べるようになります。",
    "TagFieldLoading": "ライブラリの列を読み込んでいます...",
    "TagFieldNoneFound": "タグに使える列が見つかりませんでした。ライブラリ名が正しいか、1行テキスト / 複数行テキスト / 選択肢 のいずれかの列がライブラリにあるかを確認してください。",
    "TagFieldReady": "{0} 個の列から選べます。",
    "TagSearchPageLabel": "タグ検索ページ",
    "TagSearchPageDescription": "タグをクリックしたときに開くページ。空欄なら同じページ内で検索します。例: search_tag.aspx",

    "ShowTagEditorLabel": "列名をクリックしてタグを編集できるようにする",
    "ShowEditButtonLabel": "右上に「編集」ボタンを表示する",
    "ShowOpenInAppButtonLabel": "右上に「アプリで開く」ボタンを表示する",
    "AppProtocolLabel": "URL スキーム",
    "AppProtocolDescription": "このスキームに対応したアプリが利用者の PC に登録されている必要があります。既定は spmd。",

    "LoadingMessage": "Loading...",
    "NotFoundMessage": "ファイルが見つかりません。",
    "ErrorMessage": "ファイルを読み込めませんでした。",
    "LibraryNotFoundMessage": "ドキュメントライブラリが見つかりません。Web パーツのプロパティでライブラリ名を確認してください。",
    "NotConfiguredMessage": "Web パーツのプロパティでライブラリ名と開始ファイルを設定してください。",
    "PageLabel": "ページ:",

    "TagEditLabel": "クリックしてタグを編集",
    "EditButtonLabel": "編集",
    "OpenInAppButtonLabel": "アプリで開く",


    "TagPanelTitle": "タグを編集",
    "TagTextHint": "複数のタグは ; か , で区切ってください。",
    "TagNoChoices": "この列に選択肢が登録されていません。ライブラリの列設定で追加してください。",
    "TagFieldMissingMessage": "タグの列が設定されていないか、ライブラリに存在しません。",
    "TagSaveFailedMessage": "タグを保存できませんでした。",

    "TagAddLabel": "新しいタグを追加",
    "TagAddPlaceholder": "例: 設計; 手順書",
    "TagAddDisabledPlaceholder": "この列にはタグを追加できません",
    "TagAddHint": "一覧に無いタグはここに入力します。複数は ; か , で区切ってください。",
    "TagAddDisabledHint": "この列は選択肢以外の値を受け付けません。列の設定で「選択肢に含まれていない値の入力を許可する」を有効にすると、ここから追加できるようになります。",

    "ShowPermissionsButtonLabel": "鍵アイコン（アクセス許可）を表示する",
    "PermUnknownTitle": "アクセス許可を確認・変更",
    "PermLockedTitle": "限定公開です（このページ専用の設定）。クリックして確認・変更",
    "PermUnlockedTitle": "上のフォルダーの設定を引き継いでいます。クリックして確認・変更",
    "NotFoundReasonMessage": "削除されたか、閲覧権限がない可能性があります。",
    "NotFoundTreeLabel": "このライブラリで開けるページ",
    "BackLabel": "戻る",
    "PermTitle": "アクセス許可",
    "PermInheritedFromLabel": "{0}の設定を引き継ぎ",
    "PermUniqueLabel": "限定公開",
    "PermTeamLabel": "チーム",
    "PermFolderSuffix": " フォルダー",
    "PermSearchButton": "検索",
    "PermSearchFailedMessage": "相手を検索できませんでした。",
    "PermWhoLabel": "アクセスできる相手",
    "PermRestrictLabel": "限定公開にする",
    "PermRestoreLabel": "親の設定に戻す",
    "PermConfirmTitle": "確認してください",
    "PermConfirmRestrict": "「{0}」が上のフォルダーの設定を引き継ぐのをやめます。以後、上のフォルダーの設定を変えてもここには反映されません。フォルダーの場合は、その中のフォルダーとファイルにも一緒に効きます。今の設定はそのままコピーされるので、この操作だけで誰かが見られなくなることはありません。",
    "PermConfirmRestore": "「{0}」を上のフォルダーの設定に戻します。ここで設定した内容は失われます。",
    "PermConfirmYes": "実行する",
    "PermAddLabel": "アクセスできる相手を追加",
    "PermAddPlaceholder": "グループ名または名前・メールアドレス",
    "PermAddButton": "追加",
    "PermRemoveLabel": "削除",
    "PermSearchingMessage": "検索しています...",
    "PermNoResultsMessage": "該当する相手が見つかりませんでした。",
    "PermBrokenTitle": "ここでの設定が反映されない項目",
    "PermBrokenIntro": "下の項目には、それぞれ個別のアクセス許可が設定されています。このフォルダーを限定公開にしても、下の項目は変わりません。見せたくない相手に見えたままになることがあるので、必要であれば 1 つずつ設定してください。",
    "PermFileScopeWarning": "ファイル単位の設定はライブラリ全体の動作を重くします。基本はフォルダー単位で設定し、ファイル単位は例外にしてください。",
    "PermLoadingMessage": "アクセス許可を読み込んでいます...",
    "PermLoadFailedMessage": "アクセス許可を読み込めませんでした。",
    "PermNoEffectMessage": "SharePoint はエラーを返しませんでしたが、アクセス許可の状態が変わっていません。ライブラリ側で対象の「アクセス許可の管理」を開いて実際の状態を確認してください。",
    "PermChangeFailedMessage": "アクセス許可を変更できませんでした。",
    "SearchRestrictedOnlyLabel": "限定公開のみ",
    "PermLockedShortLabel": "限定公開",
    "SearchLabel": "検索",
    "SearchTitle": "検索",
    "SearchTermPlaceholder": "検索する文字列",
    "SearchModeName": "ページ名で探す",
    "SearchModeContent": "本文で探す",
    "SearchScopeLabel": "検索するフォルダー",
    "SearchScopePlaceholder": "フォルダー (空欄ならライブラリ全体)",
    "SearchSubmitLabel": "検索",
    "SearchBusyMessage": "検索しています...",
    "SearchProgressMessage": "本文を読んでいます... {0} / {1}",
    "SearchResultCount": "{0} 件見つかりました。",
    "SearchEmptyMessage": "該当するページはありません。",
    "SearchPromptMessage": "検索する文字列を入力してください。",
    "HelpLabel": "ヘルプ",
    "ChromeFullScreenLabel": "全画面表示に切り替える",
    "ChromeSharePointLabel": "SharePoint 表示に切り替える",
    "HelpTitle": "ヘルプ",
    "HelpDocumentsTitle": "ドキュメント",
    "HelpSetupTitle": "ライブラリのコマンドの設定",
    "HelpBackLabel": "← ヘルプの目次へ",
    "HelpCommandSetIntro": "ライブラリのツールバーと右クリック メニューにコマンドを出すには、アプリ カタログの「テナント全体の拡張機能」リストに次の値で 1 行追加します。値はこのページから組み立てたものなので、そのまま貼り付けられます。",
    "HelpComponentId": "コンポーネント ID",
    "HelpLocation": "場所",
    "HelpListTemplate": "リストのテンプレート",
    "HelpComponentProperties": "コンポーネントのプロパティ",
    "HelpExtensionsList": "テナント全体の拡張機能リスト",
    "CopyLabel": "コピー",
    "CopiedLabel": "コピーしました",
    "FolderPageEmptyMessage": "このフォルダーには表示できるファイルがありません。",
    "OutlineButtonLabel": "目次（クリックでポップアップ、ダブルクリックで左に固定）",
    "OutlineTitle": "目次",
    "OutlineEmptyMessage": "このページには見出しがありません。",
    "MenuButtonLabel": "メニュー",
    "PathButtonLabel": "クリックしてファイル名・フォルダーを変更",
    "NewPageTitle": "新しいページを作成",
    "NewPageNamePlaceholder": "ファイル名",
    "NewPageFormatLabel": "形式",
    "NewPageOpenWithLabel": "作成後",
    "NewPageOpenInSharePoint": "SharePoint で編集",
    "NewPageOpenInApp": "アプリで編集",
    "CreateLabel": "作成",
    "LocationTitle": "現在の場所",
    "RootLabel": "(ライブラリのルート)",
    "FolderEmptyMessage": "このフォルダーに表示できるファイルはありません。",
    "CreateFailedMessage": "ファイルを作成できませんでした。",
    "NewPageCreatedMessage": "ページを作成しました。編集画面を開けなかったので、右上の「編集」ボタンから開いてください。",

    "RenameTitle": "ファイル名 / フォルダーの変更",
    "RenameFolderLabel": "フォルダー",
    "RenameNameLabel": "ファイル名",
    "RenameHint": "ライブラリのルートからの相対パスです。フォルダーを空欄にするとルート直下へ移動します。移動先のフォルダーは既に存在している必要があります。",
    "RenameFailedMessage": "ファイル名を変更できませんでした。",
    "InvalidNameMessage": "拡張子は .md / .markdown / .html / .htm のいずれかにしてください。",

    "HeadingCopyLabel": "この見出しへのリンクをコピー",
    "HeadingToggleLabel": "クリックで折りたたみ",
    "LinkCopiedMessage": "リンクをコピーしました",
    "CodeCopyLabel": "コードをコピー",
    "CodeCopiedMessage": "コードをコピーしました",

    "DirectiveEmptyMessage": "該当するページはありません。",

    "TagSearchTitle": "タグ:",
    "TagSearchEmpty": "このタグが付いたページはありません。",

    "OpenInAppFailedMessage": "アプリを起動できませんでした。{0}: に対応したアプリがこの PC に登録されているか確認してください。",
    "SaveLabel": "保存",
    "CancelLabel": "キャンセル",
    "CloseLabel": "閉じる"
  }
});
